apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horreum-postgres
  namespace: horreum
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem